scenario:
  name: routeros_simple_bgp
failure:
  fault_type: bgp_asn_misconfig
  cases:
  - inject:
      host_name: router1
    root_causes:
    - resource:
        kind: node
        node: router1
      fault_type: bgp_asn_misconfig
  - inject:
      host_name: router2
    root_causes:
    - resource:
        kind: node
        node: router2
      fault_type: bgp_asn_misconfig
