FROM kathara/frr:latest

RUN apt-get update && \
    apt-get install -y --no-install-recommends stress-ng isc-dhcp-server isc-dhcp-relay nftables wireguard wireguard-tools tcpdump tshark conntrack && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
