scenario:
  name: campus_lan
failure:
  fault_type: ospf_area_misconfiguration
  cases:
  - topo_size: s
    inject:
      host_name: router_core_1
    root_causes:
    - resource:
        kind: node
        node: router_core_1
      fault_type: ospf_area_misconfiguration
  - topo_size: s
    inject:
      host_name: router_core_2
    root_causes:
    - resource:
        kind: node
        node: router_core_2
      fault_type: ospf_area_misconfiguration
  - topo_size: s
    inject:
      host_name: router_core_3
    root_causes:
    - resource:
        kind: node
        node: router_core_3
      fault_type: ospf_area_misconfiguration
  - topo_size: s
    inject:
      host_name: router_dist_1_1
    root_causes:
    - resource:
        kind: node
        node: router_dist_1_1
      fault_type: ospf_area_misconfiguration
  - topo_size: s
    inject:
      host_name: router_dist_2_1
    root_causes:
    - resource:
        kind: node
        node: router_dist_2_1
      fault_type: ospf_area_misconfiguration
  - topo_size: s
    inject:
      host_name: server_access_router
    root_causes:
    - resource:
        kind: node
        node: server_access_router
      fault_type: ospf_area_misconfiguration
  - topo_size: m
    inject:
      host_name: router_core_1
    root_causes:
    - resource:
        kind: node
        node: router_core_1
      fault_type: ospf_area_misconfiguration
  - topo_size: m
    inject:
      host_name: router_core_2
    root_causes:
    - resource:
        kind: node
        node: router_core_2
      fault_type: ospf_area_misconfiguration
  - topo_size: m
    inject:
      host_name: router_core_3
    root_causes:
    - resource:
        kind: node
        node: router_core_3
      fault_type: ospf_area_misconfiguration
  - topo_size: m
    inject:
      host_name: router_dist_1_1
    root_causes:
    - resource:
        kind: node
        node: router_dist_1_1
      fault_type: ospf_area_misconfiguration
  - topo_size: m
    inject:
      host_name: router_dist_1_2
    root_causes:
    - resource:
        kind: node
        node: router_dist_1_2
      fault_type: ospf_area_misconfiguration
  - topo_size: m
    inject:
      host_name: router_dist_2_1
    root_causes:
    - resource:
        kind: node
        node: router_dist_2_1
      fault_type: ospf_area_misconfiguration
  - topo_size: m
    inject:
      host_name: router_dist_2_2
    root_causes:
    - resource:
        kind: node
        node: router_dist_2_2
      fault_type: ospf_area_misconfiguration
  - topo_size: m
    inject:
      host_name: server_access_router
    root_causes:
    - resource:
        kind: node
        node: server_access_router
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    inject:
      host_name: router_core_1
    root_causes:
    - resource:
        kind: node
        node: router_core_1
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    inject:
      host_name: router_core_2
    root_causes:
    - resource:
        kind: node
        node: router_core_2
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    inject:
      host_name: router_core_3
    root_causes:
    - resource:
        kind: node
        node: router_core_3
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    inject:
      host_name: router_dist_1_1
    root_causes:
    - resource:
        kind: node
        node: router_dist_1_1
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    inject:
      host_name: router_dist_1_2
    root_causes:
    - resource:
        kind: node
        node: router_dist_1_2
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    inject:
      host_name: router_dist_1_3
    root_causes:
    - resource:
        kind: node
        node: router_dist_1_3
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    inject:
      host_name: router_dist_1_4
    root_causes:
    - resource:
        kind: node
        node: router_dist_1_4
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    inject:
      host_name: router_dist_2_1
    root_causes:
    - resource:
        kind: node
        node: router_dist_2_1
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    inject:
      host_name: router_dist_2_2
    root_causes:
    - resource:
        kind: node
        node: router_dist_2_2
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    inject:
      host_name: router_dist_2_3
    root_causes:
    - resource:
        kind: node
        node: router_dist_2_3
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    inject:
      host_name: router_dist_2_4
    root_causes:
    - resource:
        kind: node
        node: router_dist_2_4
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    inject:
      host_name: server_access_router
    root_causes:
    - resource:
        kind: node
        node: server_access_router
      fault_type: ospf_area_misconfiguration
