scenario:
  name: isp_germany50
failure:
  fault_type: ospf_area_misconfiguration
  cases:
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: aachen
    root_causes:
    - resource:
        kind: node
        node: aachen
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: augsburg
    root_causes:
    - resource:
        kind: node
        node: augsburg
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: bayreuth
    root_causes:
    - resource:
        kind: node
        node: bayreuth
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: berlin
    root_causes:
    - resource:
        kind: node
        node: berlin
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: bielefeld
    root_causes:
    - resource:
        kind: node
        node: bielefeld
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: braunschweig
    root_causes:
    - resource:
        kind: node
        node: braunschweig
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: bremen
    root_causes:
    - resource:
        kind: node
        node: bremen
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: bremerhaven
    root_causes:
    - resource:
        kind: node
        node: bremerhaven
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: chemnitz
    root_causes:
    - resource:
        kind: node
        node: chemnitz
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: darmstadt
    root_causes:
    - resource:
        kind: node
        node: darmstadt
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: dortmund
    root_causes:
    - resource:
        kind: node
        node: dortmund
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: dresden
    root_causes:
    - resource:
        kind: node
        node: dresden
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: duesseldorf
    root_causes:
    - resource:
        kind: node
        node: duesseldorf
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: erfurt
    root_causes:
    - resource:
        kind: node
        node: erfurt
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: essen
    root_causes:
    - resource:
        kind: node
        node: essen
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: flensburg
    root_causes:
    - resource:
        kind: node
        node: flensburg
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: frankfurt
    root_causes:
    - resource:
        kind: node
        node: frankfurt
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: freiburg
    root_causes:
    - resource:
        kind: node
        node: freiburg
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: fulda
    root_causes:
    - resource:
        kind: node
        node: fulda
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: giessen
    root_causes:
    - resource:
        kind: node
        node: giessen
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: greifswald
    root_causes:
    - resource:
        kind: node
        node: greifswald
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: hamburg
    root_causes:
    - resource:
        kind: node
        node: hamburg
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: hannover
    root_causes:
    - resource:
        kind: node
        node: hannover
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: kaiserslautern
    root_causes:
    - resource:
        kind: node
        node: kaiserslautern
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: karlsruhe
    root_causes:
    - resource:
        kind: node
        node: karlsruhe
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: kassel
    root_causes:
    - resource:
        kind: node
        node: kassel
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: kempten
    root_causes:
    - resource:
        kind: node
        node: kempten
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: kiel
    root_causes:
    - resource:
        kind: node
        node: kiel
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: koblenz
    root_causes:
    - resource:
        kind: node
        node: koblenz
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: koeln
    root_causes:
    - resource:
        kind: node
        node: koeln
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: konstanz
    root_causes:
    - resource:
        kind: node
        node: konstanz
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: leipzig
    root_causes:
    - resource:
        kind: node
        node: leipzig
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: magdeburg
    root_causes:
    - resource:
        kind: node
        node: magdeburg
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: mannheim
    root_causes:
    - resource:
        kind: node
        node: mannheim
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: muenchen
    root_causes:
    - resource:
        kind: node
        node: muenchen
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: muenster
    root_causes:
    - resource:
        kind: node
        node: muenster
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: norden
    root_causes:
    - resource:
        kind: node
        node: norden
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: nuernberg
    root_causes:
    - resource:
        kind: node
        node: nuernberg
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: oldenburg
    root_causes:
    - resource:
        kind: node
        node: oldenburg
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: osnabrueck
    root_causes:
    - resource:
        kind: node
        node: osnabrueck
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: passau
    root_causes:
    - resource:
        kind: node
        node: passau
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: regensburg
    root_causes:
    - resource:
        kind: node
        node: regensburg
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: saarbruecken
    root_causes:
    - resource:
        kind: node
        node: saarbruecken
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: schwerin
    root_causes:
    - resource:
        kind: node
        node: schwerin
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: siegen
    root_causes:
    - resource:
        kind: node
        node: siegen
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: stuttgart
    root_causes:
    - resource:
        kind: node
        node: stuttgart
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: trier
    root_causes:
    - resource:
        kind: node
        node: trier
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: ulm
    root_causes:
    - resource:
        kind: node
        node: ulm
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: wesel
    root_causes:
    - resource:
        kind: node
        node: wesel
      fault_type: ospf_area_misconfiguration
  - topo_size: l
    igp: ospf
    bgp_mode: none
    rpki: false
    backend: kathara
    device_profile: frr
    inject:
      host_name: wuerzburg
    root_causes:
    - resource:
        kind: node
        node: wuerzburg
      fault_type: ospf_area_misconfiguration
